ai:
  provider: custom
  baseUrl: https://open.bigmodel.cn/api/coding/paas/v4
  apiKey: 33da1545a3814919bbdb37b22b948eef.ti6ZZG8uQTEKzS7l
  model: ''
  customModel: glm-4.6
  maxTokens: 8000
  temperature: 0.7
general:
  language: zh-CN
  theme: dark
  zoom: 1
  autoSaveSessions: true
  reconnectOnStart: false
  connectionTimeout: 30
  enableNotifications: true
  soundEnabled: true
  autoSave: true
  checkUpdates: true
terminal:
  font: Consolas
  fontSize: 14
  lineHeight: 1.2
  bell: false
  cursorBlink: true
  cursorStyle: block
  scrollback: 1000
  copyShortcut: ctrl-c
  pasteShortcut: ctrl-v
  idleTimeout: 600
  timeoutWarning: 30
  autoReconnect: false
  fontFamily: Consolas
  copyOnSelect: false
security:
  encryptPasswords: false
  sessionTimeout: 30
  confirmDangerousCommands: true
  passwordEncryption: false
aiChat:
  provider: custom
  apiKey: 33da1545a3814919bbdb37b22b948eef.ti6ZZG8uQTEKzS7l
  baseUrl: https://open.bigmodel.cn/api/coding/paas/v4
  model: ''
  customModel: glm-4.6
  maxTokens: 8000
  temperature: 0.7
  systemPromptEnabled: false
  systemPrompt: 你是一个专业的编程助手，请帮助用户解决编程问题。
  saveHistory: true
  historyRetentionDays: 30
aiCompletion:
  provider: custom
  apiKey: 33da1545a3814919bbdb37b22b948eef.ti6ZZG8uQTEKzS7l
  baseUrl: https://open.bigmodel.cn/api/coding/paas/v4
  model: ''
  customModel: glm-4.5
  autoTrigger: true
  triggerDelay: 500
  maxSuggestions: 5
  acceptOnTab: true
lastSavedProviders:
  aiChat: custom
  aiCompletion: custom
  timestamp: '2025-10-16T15:54:44.937Z'
providerPool:
  aiChat:
    openai:
      provider: openai
      apiKey: '12236666'
      baseUrl: https://api.openai.com/v1
      model: gpt-3.5-turbo
      customModel: ''
      maxTokens: 2000
      temperature: 0.7
      systemPromptEnabled: false
      systemPrompt: 你是一个专业的编程助手，请帮助用户解决编程问题。
      saveHistory: true
      historyRetentionDays: 30
      lastUpdated: '2025-10-12T16:16:01.200Z'
    custom:
      provider: custom
      apiKey: 33da1545a3814919bbdb37b22b948eef.ti6ZZG8uQTEKzS7l
      baseUrl: https://open.bigmodel.cn/api/coding/paas/v4
      model: ''
      customModel: glm-4.6
      maxTokens: 8000
      temperature: 0.7
      systemPromptEnabled: false
      systemPrompt: 你是一个专业的编程助手，请帮助用户解决编程问题。
      saveHistory: true
      historyRetentionDays: 30
      lastUpdated: '2025-10-16T15:54:44.936Z'
  aiCompletion:
    openai:
      provider: openai
      apiKey: d469275b156c4c6ba9b436d923aafcc9.LM3fUIcmUbnosM0V
      baseUrl: https://open.bigmodel.cn/api/coding/paas/v4
      model: gpt-3.5-turbo
      customModel: glm-4.5
      autoTrigger: true
      triggerDelay: 500
      maxSuggestions: 5
      acceptOnTab: true
      lastUpdated: '2025-10-12T16:23:21.257Z'
    custom:
      provider: custom
      apiKey: 33da1545a3814919bbdb37b22b948eef.ti6ZZG8uQTEKzS7l
      baseUrl: https://open.bigmodel.cn/api/coding/paas/v4
      model: ''
      customModel: glm-4.5
      autoTrigger: true
      triggerDelay: 500
      maxSuggestions: 5
      acceptOnTab: true
      lastUpdated: '2025-10-16T15:54:44.937Z'
